name: Feature Version Bump Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run feature version check script
        run: |
          python .github/scripts/version-checker.py
